# Generated by Django 5.2.6 on 2025-10-20 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(related_name='event', to=settings.AUTH_USER_MODEL),
        ),
    ]
