# Generated by Django 5.2.6 on 2025-10-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_user_event_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events_images/default_img.jpg', null=True, upload_to='events_images'),
        ),
    ]
